/* The following code was generated by JFlex 1.6.1 */

package analisador.lexico;
import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>C:/Users/Jossias Mupandza/Documents/GitHub/CompiladorParser/app/CompiladorParser/src/analisador/lexico/linguagem.lex</tt>
 */
public class AnaLex {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\14\1\6\1\10\1\11\1\7\22\0\1\14\1\51\1\12"+
    "\1\21\2\0\1\22\1\5\1\61\1\62\1\16\1\17\1\65\1\20"+
    "\1\4\1\15\1\3\11\2\1\56\1\55\1\50\1\54\1\53\2\0"+
    "\14\13\1\52\15\13\1\63\1\0\1\64\1\0\1\1\1\0\1\30"+
    "\1\13\1\32\1\43\1\25\1\41\1\45\1\34\1\42\2\13\1\33"+
    "\1\44\1\26\1\31\1\37\1\35\1\40\1\24\1\27\1\36\1\46"+
    "\3\13\1\47\1\57\1\23\1\60\7\0\1\10\u1fa2\0\1\10\1\10"+
    "\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\2\3\1\4\1\1\2\5\1\1"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\13\2"+
    "\1\15\1\1\1\16\1\1\1\17\1\1\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\3\0\1\27\2\0"+
    "\1\27\1\5\1\0\1\30\17\2\1\0\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\2\0\5\2"+
    "\1\41\12\2\2\0\1\5\4\2\1\42\2\2\1\43"+
    "\7\2\1\0\1\2\1\44\12\2\1\45\1\0\2\2"+
    "\1\46\1\47\3\2\1\50\2\2\1\51\1\52\1\2"+
    "\1\53\1\2\1\54\1\55\1\56\1\57";

  private static int [] zzUnpackAction() {
    int [] result = new int[145];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\66\0\154\0\242\0\330\0\66\0\u010e\0\66"+
    "\0\u0144\0\u017a\0\u01b0\0\66\0\66\0\66\0\66\0\66"+
    "\0\154\0\u01e6\0\u021c\0\u0252\0\u0288\0\u02be\0\u02f4\0\u032a"+
    "\0\u0360\0\u0396\0\u03cc\0\u0402\0\u0438\0\u046e\0\u04a4\0\u04da"+
    "\0\66\0\u0510\0\66\0\66\0\66\0\66\0\66\0\66"+
    "\0\66\0\u0546\0\330\0\u057c\0\u057c\0\u05b2\0\u017a\0\u017a"+
    "\0\u05e8\0\u061e\0\154\0\u0654\0\u068a\0\u06c0\0\u06f6\0\u072c"+
    "\0\u0762\0\u0798\0\u07ce\0\u0804\0\u083a\0\u0870\0\u08a6\0\u08dc"+
    "\0\u0912\0\u0948\0\u097e\0\66\0\66\0\66\0\66\0\66"+
    "\0\66\0\u0546\0\u057c\0\u09b4\0\u09ea\0\u0a20\0\u0a56\0\u0a8c"+
    "\0\u0ac2\0\u0af8\0\154\0\u0b2e\0\u0b64\0\u0b9a\0\u0bd0\0\u0c06"+
    "\0\u0c3c\0\u0c72\0\u0ca8\0\u0cde\0\u0d14\0\u0d4a\0\u0d80\0\u09b4"+
    "\0\u0db6\0\u0dec\0\u0e22\0\u0e58\0\154\0\u0e8e\0\u0ec4\0\154"+
    "\0\u0efa\0\u0f30\0\u0f66\0\u0f9c\0\u0fd2\0\u1008\0\u103e\0\u1074"+
    "\0\u10aa\0\154\0\u10e0\0\u1116\0\u114c\0\u1182\0\u11b8\0\u11ee"+
    "\0\u1224\0\u125a\0\u1290\0\u12c6\0\154\0\u12fc\0\u1332\0\u1368"+
    "\0\154\0\154\0\u139e\0\u13d4\0\u140a\0\154\0\u1440\0\u1476"+
    "\0\154\0\66\0\u14ac\0\154\0\u14e2\0\154\0\154\0\154"+
    "\0\154";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[145];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\0\1\10\1\12\1\3\1\10\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\4\3\1\24"+
    "\1\25\3\3\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\3\1\34\1\3\1\35\1\36\1\3\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\1\47\1\50"+
    "\1\51\67\0\3\3\7\0\1\3\7\0\25\3\2\0"+
    "\1\3\15\0\2\4\1\52\63\0\2\53\1\52\61\0"+
    "\5\54\1\55\4\0\1\54\1\56\7\54\25\56\2\54"+
    "\1\56\13\54\6\0\1\10\57\0\6\57\4\0\1\60"+
    "\53\57\15\0\1\61\1\62\50\0\3\3\7\0\1\3"+
    "\7\0\2\3\1\63\22\3\2\0\1\3\14\0\3\3"+
    "\7\0\1\3\7\0\1\3\1\64\1\3\1\65\21\3"+
    "\2\0\1\3\14\0\3\3\7\0\1\3\7\0\2\3"+
    "\1\66\2\3\1\67\17\3\2\0\1\3\14\0\3\3"+
    "\7\0\1\3\7\0\6\3\1\70\10\3\1\71\5\3"+
    "\2\0\1\3\14\0\3\3\7\0\1\3\7\0\5\3"+
    "\1\72\7\3\1\73\7\3\2\0\1\3\14\0\3\3"+
    "\7\0\1\3\7\0\2\3\1\74\22\3\2\0\1\3"+
    "\14\0\3\3\7\0\1\3\7\0\5\3\1\75\5\3"+
    "\1\76\11\3\2\0\1\3\14\0\3\3\7\0\1\3"+
    "\7\0\3\3\1\77\21\3\2\0\1\3\14\0\3\3"+
    "\7\0\1\3\7\0\2\3\1\100\22\3\2\0\1\3"+
    "\14\0\3\3\7\0\1\3\7\0\5\3\1\101\17\3"+
    "\2\0\1\3\14\0\3\3\7\0\1\3\7\0\5\3"+
    "\1\102\17\3\2\0\1\3\64\0\1\103\1\0\1\104"+
    "\1\105\64\0\1\106\66\0\1\107\65\0\1\110\65\0"+
    "\1\111\13\0\2\112\62\0\5\54\1\55\4\0\61\54"+
    "\1\113\4\0\54\54\6\61\1\10\1\11\56\61\16\114"+
    "\1\115\47\114\1\0\3\3\7\0\1\3\7\0\7\3"+
    "\1\116\15\3\2\0\1\3\14\0\3\3\7\0\1\3"+
    "\7\0\4\3\1\117\5\3\1\120\12\3\2\0\1\3"+
    "\14\0\3\3\7\0\1\3\7\0\3\3\1\121\21\3"+
    "\2\0\1\3\14\0\3\3\7\0\1\3\7\0\1\3"+
    "\1\122\13\3\1\123\7\3\2\0\1\3\14\0\3\3"+
    "\7\0\1\3\7\0\22\3\1\124\2\3\2\0\1\3"+
    "\14\0\3\3\7\0\1\3\7\0\4\3\1\125\20\3"+
    "\2\0\1\3\14\0\3\3\7\0\1\3\7\0\15\3"+
    "\1\126\7\3\2\0\1\3\14\0\3\3\7\0\1\3"+
    "\7\0\6\3\1\127\16\3\2\0\1\3\14\0\3\3"+
    "\7\0\1\3\7\0\4\3\1\130\20\3\2\0\1\3"+
    "\14\0\3\3\7\0\1\3\7\0\7\3\1\126\15\3"+
    "\2\0\1\3\14\0\3\3\7\0\1\3\7\0\3\3"+
    "\1\131\21\3\2\0\1\3\14\0\3\3\7\0\1\3"+
    "\7\0\4\3\1\132\20\3\2\0\1\3\14\0\3\3"+
    "\7\0\1\3\7\0\7\3\1\133\15\3\2\0\1\3"+
    "\14\0\3\3\7\0\1\3\7\0\4\3\1\134\20\3"+
    "\2\0\1\3\14\0\3\3\7\0\1\3\7\0\24\3"+
    "\1\135\2\0\1\3\65\0\1\136\13\0\16\114\1\137"+
    "\64\114\1\140\1\137\47\114\1\0\3\3\7\0\1\3"+
    "\7\0\6\3\1\141\16\3\2\0\1\3\14\0\3\3"+
    "\7\0\1\3\7\0\5\3\1\142\17\3\2\0\1\3"+
    "\14\0\3\3\7\0\1\3\7\0\13\3\1\143\11\3"+
    "\2\0\1\3\14\0\3\3\7\0\1\3\7\0\4\3"+
    "\1\144\20\3\2\0\1\3\14\0\3\3\7\0\1\3"+
    "\7\0\6\3\1\145\16\3\2\0\1\3\14\0\3\3"+
    "\7\0\1\3\7\0\17\3\1\146\5\3\2\0\1\3"+
    "\14\0\3\3\7\0\1\3\7\0\2\3\1\147\22\3"+
    "\2\0\1\3\14\0\3\3\7\0\1\3\7\0\5\3"+
    "\1\150\17\3\2\0\1\3\14\0\3\3\7\0\1\3"+
    "\7\0\22\3\1\151\2\3\2\0\1\3\14\0\3\3"+
    "\7\0\1\3\7\0\6\3\1\152\16\3\2\0\1\3"+
    "\14\0\3\3\7\0\1\3\7\0\7\3\1\153\15\3"+
    "\2\0\1\3\14\0\3\3\7\0\1\3\7\0\2\3"+
    "\1\154\22\3\2\0\1\3\14\0\3\3\7\0\1\3"+
    "\7\0\17\3\1\155\5\3\2\0\1\3\14\0\3\3"+
    "\7\0\1\3\7\0\15\3\1\156\7\3\2\0\1\3"+
    "\14\0\3\3\7\0\1\3\7\0\17\3\1\157\5\3"+
    "\2\0\1\3\51\0\1\160\27\0\15\114\1\10\1\137"+
    "\47\114\1\0\3\3\7\0\1\3\7\0\10\3\1\161"+
    "\14\3\2\0\1\3\14\0\3\3\7\0\1\3\7\0"+
    "\6\3\1\162\16\3\2\0\1\3\14\0\3\3\7\0"+
    "\1\3\7\0\5\3\1\163\17\3\2\0\1\3\14\0"+
    "\3\3\7\0\1\3\7\0\15\3\1\164\7\3\2\0"+
    "\1\3\14\0\3\3\7\0\1\3\7\0\7\3\1\165"+
    "\15\3\2\0\1\3\14\0\3\3\7\0\1\3\7\0"+
    "\15\3\1\166\7\3\2\0\1\3\14\0\3\3\7\0"+
    "\1\3\7\0\15\3\1\167\7\3\2\0\1\3\14\0"+
    "\3\3\7\0\1\3\7\0\15\3\1\170\7\3\2\0"+
    "\1\3\14\0\3\3\7\0\1\3\7\0\5\3\1\171"+
    "\17\3\2\0\1\3\14\0\3\3\7\0\1\3\7\0"+
    "\17\3\1\172\5\3\2\0\1\3\14\0\3\3\7\0"+
    "\1\3\7\0\21\3\1\173\3\3\2\0\1\3\14\0"+
    "\3\3\7\0\1\3\7\0\17\3\1\174\5\3\2\0"+
    "\1\3\14\0\3\3\7\0\1\3\7\0\6\3\1\175"+
    "\16\3\2\0\1\3\45\0\1\176\34\0\3\3\7\0"+
    "\1\3\7\0\11\3\1\177\13\3\2\0\1\3\14\0"+
    "\3\3\7\0\1\3\7\0\3\3\1\200\21\3\2\0"+
    "\1\3\14\0\3\3\7\0\1\3\7\0\6\3\1\201"+
    "\16\3\2\0\1\3\14\0\3\3\7\0\1\3\7\0"+
    "\6\3\1\202\16\3\2\0\1\3\14\0\3\3\7\0"+
    "\1\3\7\0\5\3\1\203\17\3\2\0\1\3\14\0"+
    "\3\3\7\0\1\3\7\0\5\3\1\204\17\3\2\0"+
    "\1\3\14\0\3\3\7\0\1\3\7\0\3\3\1\205"+
    "\21\3\2\0\1\3\14\0\3\3\7\0\1\3\7\0"+
    "\6\3\1\206\16\3\2\0\1\3\14\0\3\3\7\0"+
    "\1\3\7\0\15\3\1\207\7\3\2\0\1\3\14\0"+
    "\3\3\7\0\1\3\7\0\5\3\1\210\17\3\2\0"+
    "\1\3\14\0\3\3\7\0\1\3\7\0\24\3\1\211"+
    "\2\0\1\3\44\0\1\212\35\0\3\3\7\0\1\3"+
    "\7\0\5\3\1\145\17\3\2\0\1\3\14\0\3\3"+
    "\7\0\1\3\7\0\4\3\1\213\20\3\2\0\1\3"+
    "\14\0\3\3\7\0\1\3\7\0\10\3\1\214\14\3"+
    "\2\0\1\3\14\0\3\3\7\0\1\3\7\0\21\3"+
    "\1\215\3\3\2\0\1\3\14\0\3\3\7\0\1\3"+
    "\7\0\2\3\1\216\22\3\2\0\1\3\14\0\3\3"+
    "\7\0\1\3\7\0\6\3\1\217\16\3\2\0\1\3"+
    "\14\0\3\3\7\0\1\3\7\0\10\3\1\220\14\3"+
    "\2\0\1\3\14\0\3\3\7\0\1\3\7\0\6\3"+
    "\1\150\16\3\2\0\1\3\14\0\3\3\7\0\1\3"+
    "\7\0\5\3\1\221\17\3\2\0\1\3\13\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5400];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\1\11\1\1\1\11\3\1\5\11"+
    "\20\1\1\11\1\1\7\11\3\0\1\1\2\0\2\1"+
    "\1\0\20\1\1\0\6\11\2\1\2\0\20\1\2\0"+
    "\20\1\1\0\15\1\1\0\13\1\1\11\7\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[145];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
/* funcoes e variaveis  */ 



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AnaLex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 174) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public MucofotiToken yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new RuntimeException("Caractere invalido \"" + yytext() +        
                            "\" na linha " + yyline + ", coluna " + yycolumn);
            }
          case 48: break;
          case 2: 
            { return new MucofotiToken(yytext(),yyline, "Identificador");
            }
          case 49: break;
          case 3: 
            { return new MucofotiToken(yytext(),yyline, "Numero inteiro");
            }
          case 50: break;
          case 4: 
            { return new MucofotiToken(yytext(),yyline, "Caracter especial - Ponto");
            }
          case 51: break;
          case 5: 
            { /* ignore */
            }
          case 52: break;
          case 6: 
            { return new MucofotiToken(yytext(),yyline, "Operador Aritmetico - Divisao");
            }
          case 53: break;
          case 7: 
            { return new MucofotiToken(yytext(),yyline, "Operador Aritmetico - Multiplicacao");
            }
          case 54: break;
          case 8: 
            { return new MucofotiToken(yytext(),yyline, "Operador Aritmetico - Adicao");
            }
          case 55: break;
          case 9: 
            { return new MucofotiToken(yytext(),yyline, "Operador Aritmetico - Subtracao");
            }
          case 56: break;
          case 10: 
            { return new MucofotiToken(yytext(),yyline, "Operador Aritmetico - Resto da Devisao");
            }
          case 57: break;
          case 11: 
            { return new MucofotiToken(yytext(),yyline, "Operador Logico - E");
            }
          case 58: break;
          case 12: 
            { return new MucofotiToken(yytext(),yyline, "Operador Logico - OU");
            }
          case 59: break;
          case 13: 
            { return new MucofotiToken(yytext(),yyline, "Operador Relacional - Menor");
            }
          case 60: break;
          case 14: 
            { return new MucofotiToken(yytext(),yyline, "Operador Relacional - Maior");
            }
          case 61: break;
          case 15: 
            { return new MucofotiToken(yytext(),yyline, "Ponto e virgula");
            }
          case 62: break;
          case 16: 
            { return new MucofotiToken(yytext(),yyline, "Caracter especial - Abre chave");
            }
          case 63: break;
          case 17: 
            { return new MucofotiToken(yytext(),yyline, "Caracter especial - Fecha chave");
            }
          case 64: break;
          case 18: 
            { return new MucofotiToken(yytext(),yyline, "Caracter especial - Abre Par");
            }
          case 65: break;
          case 19: 
            { return new MucofotiToken(yytext(),yyline, "Caracter especial - Fecha Par");
            }
          case 66: break;
          case 20: 
            { return new MucofotiToken(yytext(),yyline, "Caracter especial - Abre Par Recto");
            }
          case 67: break;
          case 21: 
            { return new MucofotiToken(yytext(),yyline, "Caracter especial - Fecha Par Recto");
            }
          case 68: break;
          case 22: 
            { return new MucofotiToken(yytext(),yyline, "Caracter especial - Virgula");
            }
          case 69: break;
          case 23: 
            { return new MucofotiToken(yytext(),yyline, "Cadeia de Caracteres/Literal");
            }
          case 70: break;
          case 24: 
            { return new MucofotiToken(yytext(),yyline, "Instucao de selecao simples");
            }
          case 71: break;
          case 25: 
            { return new MucofotiToken(yytext(),yyline, "Operador Relacional - Diferente");
            }
          case 72: break;
          case 26: 
            { return new MucofotiToken(yytext(),yyline, "Operador Relacional - Menor ou igual");
            }
          case 73: break;
          case 27: 
            { return new MucofotiToken(yytext(),yyline, "Indica fim do programa");
            }
          case 74: break;
          case 28: 
            { return new MucofotiToken(yytext(),yyline, "Operador Relacional - Maior ou igual");
            }
          case 75: break;
          case 29: 
            { return new MucofotiToken(yytext(),yyline, "Operador Relacional - Igual");
            }
          case 76: break;
          case 30: 
            { return new MucofotiToken(yytext(),yyline, "Atribuicao");
            }
          case 77: break;
          case 31: 
            { return new MucofotiToken(yytext(),yyline, "Ponto Flutuante");
            }
          case 78: break;
          case 32: 
            { return new MucofotiToken(yytext(),yyline, "Caracter");
            }
          case 79: break;
          case 33: 
            { return new MucofotiToken(yytext(),yyline, "Tipo de dado para caracter");
            }
          case 80: break;
          case 34: 
            { return new MucofotiToken(yytext(),yyline, "Instucao de selecao multipla");
            }
          case 81: break;
          case 35: 
            { return new MucofotiToken(yytext(),yyline, "estrutura de repeticao");
            }
          case 82: break;
          case 36: 
            { return new MucofotiToken(yytext(),yyline, "Instrucao de selecção em alternativa");
            }
          case 83: break;
          case 37: 
            { return new MucofotiToken(yytext(),yyline, "Subprograma sem retorno");
            }
          case 84: break;
          case 38: 
            { return new MucofotiToken(yytext(),yyline, "Primeira função executada num programa mucofoti");
            }
          case 85: break;
          case 39: 
            { return new MucofotiToken(yytext(),yyline, "Tipo de dado para valores binarios(verdade ou falso)");
            }
          case 86: break;
          case 40: 
            { return new MucofotiToken(yytext(),yyline, "Subprograma (funcao ou procedimento)");
            }
          case 87: break;
          case 41: 
            { return new MucofotiToken(yytext(),yyline, "Estrutura de dados");
            }
          case 88: break;
          case 42: 
            { return new MucofotiToken(yytext(),yyline, "Indica inicio do programa");
            }
          case 89: break;
          case 43: 
            { return new MucofotiToken(yytext(),yyline, "Tipo de dado para literal/cadeia de caracteres");
            }
          case 90: break;
          case 44: 
            { return new MucofotiToken(yytext(),yyline, "Indica retorna um valor");
            }
          case 91: break;
          case 45: 
            { return new MucofotiToken(yytext(),yyline, "Tipo de dado para numeros inteiro");
            }
          case 92: break;
          case 46: 
            { return new MucofotiToken(yytext(),yyline, "Tipo de dado para numeros decimais");
            }
          case 93: break;
          case 47: 
            { return new MucofotiToken(yytext(),yyline, "Palavra que inicia o programa fonte");
            }
          case 94: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
